version: "3.8"

services:
  server:
    build: ./server
    command: pdm run python src/main_server.py
    depends_on:
      - db
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST
      - SESP_PORT_HANDSHAKE
      - SESP_PORT_TCP
      - SESP_PORT_UDP
      - SESP_UDP_TIMEOUT
      - SESP_TCP_TIMEOUT
      - DEBUG
    ports:
      - ${SESP_PORT_TCP}:${SESP_PORT_TCP}
      - ${SESP_PORT_HANDSHAKE}:${SESP_PORT_HANDSHAKE}
      - ${SESP_PORT_UDP}:${SESP_PORT_UDP}/udp

  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db_data:
